steps:
  # Docker Build & Push
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud builds submit --tag "asia-south1-docker.pkg.dev/team-synthify/synthify/synthify-paper-app:dvmdov"


  
