steps:
  # Docker Build & Push
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud builds submit --tag "asia-south1-docker.pkg.dev/team-synthify/synthify/synthify-paper-app:${TAG}"
    env:
     - 'TAG=$SHORT_SHA'

   

  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud run deploy synthify-paper-app --image "asia-south1-docker.pkg.dev/team-synthify/synthify/synthify-paper-app:${TAG}" --region asia-south1 --set-env-vars=GCP_PROJECT=team-synthify,GCP_REGION=asia-south1
    env:
     - 'TAG=$SHORT_SHA'

  
